"""
example_adjoint.py
==================
Minimal example: compute a sensitivity kernel with the standalone fd2d solver.

Usage
-----
    python example_adjoint.py

Pre-requisites:
    • Model files in examples/forward/model_true/
    • A pre-existing set of observed / reference traces in
      examples/forward/traces/  (e.g. generated by example_forward.py with
      model_true, saved via output_traces → renamed to traces/).
    • If no 'traces' key is given in *path* the solver will generate them
      from model_true automatically before computing the kernel.
"""

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent))

from fd2d import FD2D

# ------------------------------------------------------------------ config ---
config = {
    # time integration
    'nt': 4800,
    'dt': 0.06,

    # wave physics
    'sh':  'yes',
    'psv': 'no',

    # absorbing boundaries
    'abs_top':    'no',
    'abs_bottom': 'yes',
    'abs_left':   'yes',
    'abs_right':  'yes',
    'abs_width':  20,
    'abs_alpha':  0.015,

    # execution (one source per task for adjoint)
    'threads_per_block': 512,
    'combine_sources':   'no',

    # adjoint-specific
    'adjoint_interval': 10,
    'smooth':           5,

    # output
    'save_coordinates': False,
    'save_snapshot':    0,
}

# ------------------------------------------------------------------ paths ----
base = 'examples/forward'
path = {
    'sources':    base + '/sources.dat',
    'stations':   base + '/stations.dat',
    'model_init': base + '/model_init',   # perturbed model to compute gradient for
    'model_true': base + '/model_true',
    'traces':     base + '/traces',        # observed / reference traces
    'output':     base + '/output',
}

# ------------------------------------------------------------------ run ------
# Load the *initial* model (the one we are inverting)
solver = FD2D(config, path)
solver.import_model(model_true=False)
solver.import_sources()
solver.import_stations()

# Load reference traces (observed data)
solver.import_traces()

# Run forward + adjoint for all sources; returns smoothed kernel and misfit
k_mu, misfit, mu = solver.compute_gradient()

print('Misfit          : %.4f' % misfit)
print('Max |k_mu|      : %.4e' % abs(k_mu).max())
print('Kernel shape    :', k_mu.shape, '(flat, nx*nz)')
